name: Terraform CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # This allows the job to request an ID token for authentication

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0  # Change to the required version

      - name: Azure Login
        uses: azure/login@v1
        with:
                allow-no-subscriptions: true  # This helps in scenarios where no subscriptions are available
                enable-AzPSSession: false      # OIDC does not require this
                environment: azurecloud        # Correct cloud environment
                audience: api://AzureADTokenExchange  # Use this for OIDC, but it can often be omitted for simplicity


      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Output
        run: terraform output
